-- CreateTable
CREATE TABLE `SchoolStat` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `year` INTEGER UNSIGNED NOT NULL,
    `students` INTEGER UNSIGNED NOT NULL,
    `classes` INTEGER UNSIGNED NOT NULL,
    `teachers` INTEGER UNSIGNED NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SchoolProfile` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `visi` TEXT NOT NULL,
    `misi` TEXT NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
